spring.application.name=gateway

server.port=8070

# ROUTES

# USER SERVICE
spring.cloud.gateway.server.webflux.routes[0].id=userService
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8763
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**
#spring.cloud.gateway.server.webflux.routes[0].filters[0]=StripPrefix=1

# category service
spring.cloud.gateway.server.webflux.routes[1].id=categoryService
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8762
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/categories/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=0

#  event service
spring.cloud.gateway.server.webflux.routes[2].id=eventService
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8765
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/events/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=0

# reservation service
spring.cloud.gateway.server.webflux.routes[3].id=reservationService
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8764
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/reservations/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=StripPrefix=0

# local service
spring.cloud.gateway.server.webflux.routes[4].id=localService
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8766
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/locals/**
spring.cloud.gateway.server.webflux.routes[4].filters[0]=StripPrefix=0


# SECURITY (Keycloak)
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/MedeNext-app
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/EventProject/protocol/openid-connect/certs


spring.main.allow-bean-definition-overriding=true
